# Generated by Django 4.2 on 2023-09-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=200)),
                (
                    "date_uploaded",
                    models.DateTimeField(
                        db_comment="date and time when file was uploaded"
                    ),
                ),
            ],
        ),
    ]
